// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTzuq7-2NRP6NJ0YYxFQXv1LaqRPnbqQc',
    appId: '1:871586996697:web:bd6445f3f9ec09fd4d79c8',
    messagingSenderId: '871586996697',
    projectId: 'devin-hrms',
    authDomain: 'devin-hrms.firebaseapp.com',
    storageBucket: 'devin-hrms.firebasestorage.app',
    measurementId: 'G-DZT1Y5V342',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEzsGi1RASiYLuvSVoAVbq5rqcFnZvL_U',
    appId: '1:871586996697:android:fab81cf31c2753074d79c8',
    messagingSenderId: '871586996697',
    projectId: 'devin-hrms',
    storageBucket: 'devin-hrms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlAi-82B9OEUrUPcRPpDMTKpfjfiE1ANc',
    appId: '1:871586996697:ios:609e0f94cc7ec2b04d79c8',
    messagingSenderId: '871586996697',
    projectId: 'devin-hrms',
    storageBucket: 'devin-hrms.firebasestorage.app',
    iosBundleId: 'com.devinsoft.hrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlAi-82B9OEUrUPcRPpDMTKpfjfiE1ANc',
    appId: '1:871586996697:ios:9559feb5b84a7ce04d79c8',
    messagingSenderId: '871586996697',
    projectId: 'devin-hrms',
    storageBucket: 'devin-hrms.firebasestorage.app',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTzuq7-2NRP6NJ0YYxFQXv1LaqRPnbqQc',
    appId: '1:871586996697:web:b215f098b2749aba4d79c8',
    messagingSenderId: '871586996697',
    projectId: 'devin-hrms',
    authDomain: 'devin-hrms.firebaseapp.com',
    storageBucket: 'devin-hrms.firebasestorage.app',
    measurementId: 'G-DYKXW8LH38',
  );
}
